name: 'Push: terraform execution'
on:
  push:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Configure ssh creds
        run: git config --global url."https://oauth2:$GH_TOKEN@github.com/SolalVall/terraform-dynatrace-modules.git".insteadOf "git@github.com:SolalVall/terraform-dynatrace-modules.git"
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git config --list --show-origin
        shell: bash

      - run: cat ~/.gitconfig
        shell: bash

      - name: Run Terraform
        uses: SolalVall/action-terraform@develop
        with:
          directory: terraform
          tf_version: 1.4.6
          tf_init: true
          tf_lint: true
          tf_plan: true
