name: 'Pull-Request: terraform verifications'
on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**.tf'

jobs:
  terraform-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Test action
        uses: SolalVall/action-terraform@v0.0.4
        with:
          directory: terraform
          tf_version: 1.4.6
          tf_init: true
          tf_lint: true
          tf_plan: true
