name: 'Pull-Request: terraform verifications'
on:
  push:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Configure ssh creds
        run: git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/SolalVall/terraform-dynatrace-modules.git".insteadOf "ssh://git@github.com/SolalVall/terraform-dynatrace-modules.git"

      - name: Run Terraform
        uses: SolalVall/action-terraform@v0.0.4
        with:
          directory: terraform
          tf_version: 1.4.6
          tf_init: true
          tf_lint: true
          tf_plan: true
