name: 'Push: terraform execution'
on:
  push:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  generate-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Configure ssh creds
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/SolalVall/terraform-dynatrace-modules.git".insteadOf "ssh://git@github.com/SolalVall/terraform-dynatrace-modules.git"
          #  env:
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run Terraform
        uses: SolalVall/action-terraform@develop
        with:
          directory: terraform
          tf_version: 1.4.6
          tf_init: true
          tf_lint: true
          tf_plan: true
