name: 'Push: terraform execution'
on:
  push:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['stage', 'production']
    environment:
      name: ${{ matrix.environment }}
    env:
      DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
      DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Configure ssh creds
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/SolalVall/terraform-dynatrace-modules.git".insteadOf "ssh://git@github.com/SolalVall/terraform-dynatrace-modules.git"

      - name: Setup GCS bucket
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCS_JSON }}'

      - name: Run Terraform
        uses: SolalVall/action-terraform@main
        with:
          directory: terraform/${{ matrix.environment }}
          tf_version: 1.4.6
          tf_init: true
          tf_lint: true
          tf_plan: true

  apply:
    runs-on: ubuntu-latest
    needs: plan
    strategy:
      matrix:
        environment: ['stage', 'production']
    environment:
      name: ${{ matrix.environment }}
    env:
      DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
      DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Configure ssh creds
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/SolalVall/terraform-dynatrace-modules.git".insteadOf "ssh://git@github.com/SolalVall/terraform-dynatrace-modules.git"

      - name: Setup GCS bucket
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCS_JSON }}'

      - name: Run Terraform
        uses: SolalVall/action-terraform@main
        with:
          directory: terraform/${{ matrix.environment }}
          tf_version: 1.4.6
          tf_init: true
          tf_apply: true
